version: 2
project_name: mac-port-bar
builds:
  - binary: mac-port-bar
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - repository:
      owner: lfx
      name: homebrew-tools
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    
    # The directory inside the tap repository
    directory: Formula

    # Metadata
    description: "Lightweight macOS menu bar utility listing locally running HTTP services"
    homepage: "https://github.com/lfx/mac-port-bar"
    # (Optional) Service block for background processes
    service: |
      run opt_bin/"mac-port-bar"
      keep_alive successful_exit: false
      log_path var/"log/mac-port-bar.log"
      error_log_path var/"log/mac-port-bar.log"

    # Custom install or test instructions if necessary
    test: |
      assert_path_exists bin/"mac-port-bar"
      assert_predicate bin/"mac-port-bar", :executable?
